application: ctst
version: 1
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: common-apps/djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: common-apps/django/contrib/admin/media

- url: /.*
  script: common-apps/djangoappengine/main/main.py
